# Generated by Django 2.2 on 2020-01-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('item_url', models.TextField()),
                ('email2', models.CharField(max_length=60)),
                ('granted_item', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grantor', models.ManyToManyField(related_name='sugar', to='app.User')),
                ('submitted_by', models.ForeignKey(on_delete='CASCADE', related_name='gifts', to='app.User')),
            ],
        ),
    ]
