# Generated by Django 2.2 on 2020-01-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='price',
            field=models.IntegerField(),
        ),
    ]
