# Generated by Django 2.2 on 2020-01-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200130_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
